version: '3.4'

services:
  postgres:
    image: postgres
    ports:
      - "54321:54321"

  webpacker:
    build:
      context: .
      dockerfile: ./.docerenv/Dockerfile
      args:
          RUBY_VERSION: '2.6.3'
          PG_MAJOR: '11'
          NODE_MAJOR: '11'
          YARN_VERSION: '1.17.3'
          BUNDLER_VERSION: '2.0.2'
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: ./.docerenv/Dockerfile
      args:
          RUBY_VERSION: '2.6.3'
          PG_MAJOR: '11'
          NODE_MAJOR: '11'
          YARN_VERSION: '1.17.3'
          BUNDLER_VERSION: '2.0.2'
    image: construbem:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - PSQL_HISTFILE=/app/log/.psql_history
      - EDITOR=vi
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - webpacker
